[general]
; 基础设置
mixed-port=7890
redir-port=7892
tproxy-port=7893
allow-lan=true
mode=Rule
log-level=info
ipv6=true
external-controller=9999
external-ui=ui
external-ui-url=https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip

; TUN & 实验性设置
tun={enable: true, stack: system, device: utun, auto-route: false, auto-detect-interface: false}
experimental={ignore-resolve-fail: true, interface-name: en0}
unified-delay=true
tcp-concurrent=true

; DNS 设置
dns-enable=true
dns-listen=:1053
dns-ipv6=true
dns-nameserver=https://dns.alidns.com/dns-query, https://doh.pub/dns-query, 8.8.8.8
dns-fallback=https://1.1.1.1/dns-query, https://8.8.8.8/dns-query
dns-enhanced-mode=fake-ip
dns-fake-ip-range=198.18.0.1/16
dns-fake-ip-range6=fc00::/16
dns-respect-rules=true

[proxy_group]
; 1. 策略组定义
🧪 IPv6 测试:select, []proxy, url=http://ipv6.google.com/generate_204, interval=300
🚀 默认代理:select, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT
🤖 AI:select, 🔯 美国故转, 🔯 日本故转, 🔯 狮城故转, ♻️ 日本自动, ♻️ 狮城自动, ♻️ 美国自动, ♻️ 自动选择, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点
🍀 Google:select, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, DIRECT
📹 YouTube:select, 🔯 香港故转, 🔯 美国故转, 🔯 日本故转, 🔯 狮城故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇺🇲 美国节点, 🌐 全部节点
🎥 NETFLIX:select, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT
🎬 Emby:select, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT
🍎 苹果服务:select, DIRECT, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点
👨🏿‍💻 GitHub:select, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点, DIRECT
📲 Telegram:select, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🌐 全部节点
🐬 OneDrive:select, DIRECT, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点
🪟 Microsoft:select, DIRECT, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点, 🌐 全部节点
🎵 TikTok:select, 🔯 日本故转, 🔯 狮城故转, 🔯 美国故转, ♻️ 自动选择, 🇯🇵 日本节点, 🇸🇬 狮城节点, 🇺🇲 美国节点
🎵 Spotify:select, 🔯 美国故转, 🔯 香港故转, 🔯 日本故转, 🔯 狮城故转, ♻️ 自动选择, DIRECT
🐟 漏网之鱼:select, 🚀 默认代理, DIRECT

; 2. 节点筛选
🇭🇰 香港节点:select, []proxy, filter=(?i)港|HK|Hong
🇯🇵 日本节点:select, []proxy, filter=(?i)日|JP|Japan
🇸🇬 狮城节点:select, []proxy, filter=(?i)新|SG|Singapore
🇺🇲 美国节点:select, []proxy, filter=(?i)美|US|States
🔯 香港故转:fallback, []proxy, filter=(?i)港|HK|Hong, url=http://www.gstatic.com/generate_204, interval=300
🔯 日本故转:fallback, []proxy, filter=(?i)日|JP|Japan, url=http://www.gstatic.com/generate_204, interval=300
🔯 狮城故转:fallback, []proxy, filter=(?i)新|SG|Singapore, url=http://www.gstatic.com/generate_204, interval=300
🔯 美国故转:fallback, []proxy, filter=(?i)美|US|States, url=http://www.gstatic.com/generate_204, interval=300
♻️ 日本自动:url-test, []proxy, filter=(?i)日|JP|Japan, tolerance=20, interval=1800
♻️ 狮城自动:url-test, []proxy, filter=(?i)新|SG|Singapore, tolerance=20, interval=1800
♻️ 美国自动:url-test, []proxy, filter=(?i)美|US|States, tolerance=20, interval=1800
♻️ 自动选择:url-test, []proxy, tolerance=20, interval=1800
🌐 全部节点:select, []proxy

[rule]
; 自定义直连
DOMAIN-SUFFIX,xxttq.com,DIRECT
DOMAIN-SUFFIX,beupisp.com,DIRECT

; 规则集分流
RULE-SET,private_domain,DIRECT
RULE-SET,ai,🤖 AI
RULE-SET,youtube_domain,📹 YouTube
RULE-SET,google_domain,🍀 Google
RULE-SET,github_domain,👨🏿‍💻 GitHub
RULE-SET,telegram_domain,📲 Telegram
RULE-SET,netflix_domain,🎥 NETFLIX
RULE-SET,spotify,🎵 Spotify
RULE-SET,tiktok_domain,🎵 TikTok
RULE-SET,emby,🎬 Emby
RULE-SET,onedrive_domain,🐬 OneDrive
RULE-SET,microsoft_domain,🪟 Microsoft
RULE-SET,apple_domain,🍎 苹果服务
RULE-SET,proxylite,🚀 默认代理
RULE-SET,cn_domain,DIRECT
RULE-SET,cn_ip,DIRECT
RULE-SET,cn,DIRECT
GEOIP,lan,DIRECT,no-resolve
GEOIP,CN,DIRECT,no-resolve
MATCH,🐟 漏网之鱼
